### ISSUE TITLE
MODULE REQUEST: ChanServ MVOICE/MOP

### ISSUE THREAD

**Issue by siniStar7boy** [XthemeOrg/Xtheme#11]
NOTE: This module was requested by Maro in #Xtheme without a GitHub account. 
# ChanServ > MVOICE / MOP 
(Mass voice and/or Mass op a channel) 
**Intentions: Allows channel operators to mass voice or mass op a channel. **

**I would like to get more discussion on this -- if anyone has an opinion.**  While I can't see the use for such a module,  _would this be useful or just command bloat?_

**Comment by selangor** [comment]
No need @siniStar7boy
How about you @mohdschizo ?

**Comment by mohdschizo** [comment]
@siniStar7boy @selangor i think this kind of modules (mass voice/op) is more to mIRC addons. dont know what others think.

**Comment by siniStar7boy** [comment]
I agree.  The requested functionality is already possible with IRC clients.  Closing this issue as it feels like command bloat to me.

**Comment by siniStar7boy** [comment]
Re-opening for potentially adding in v7.5.0.  _The module(s) will not be enabled by default_, but will exist for those that desire them,

**Comment by siniStar7boy** [comment]
Though I do not necessarily agree with _all_ of them, I am sure they will be requested or should at least be included with the new **MASS** command as _options_.

**Option To-Do List:**  
- [ ] Mass Voice
- [ ] Mass Halfop
- [x] Mass OP
- [x] Mass Protect
- [x] Mass Owner
