### ISSUE TITLE
MODULE REQUEST : NickServ Set BlockSendPass On / Off

### ISSUE THREAD

**Issue by selangor** [XthemeOrg/Xtheme#14]
I would like to request modules /NickServ Set Blocksendpass On / Off

same like
-NickServ- BLOCKSENDPASS   Blocks non-IRCOps from doing a SENDPASS on your account

if i set /ns set blocksendpass on
-NickServ- The BLOCKSENDPASS flag has been set for account selangor

and if i set /ns set blocksendpass off
-NickServ- The BLOCKSENDPASS flag has been removed for account selangor

if i use /ns sendpass mohdschizo
 -NickServ- This operation could not be performed on mohdschizo because they have BLOCKSENDPASS enabled.

and at /ns info mohdschizo
-NickServ- Flags      : HideMail, NeverOp, NeverGroup, NoGreet, BlockSendpass

**Comment by siniStar7boy** [comment]
Sounds good..  Will implement as soon as I'm feeling better.  (Thanks for the feedback!)

**Comment by selangor** [comment]
You're welcome @siniStar7boy

**Comment by siniStar7boy** [comment]
Initially, I liked this idea..  After writing the code for it and thinking further and discussing further, I feel like this is not a good idea in the long run.    
_(While likely only a handful of users would use this functionality, it then could lead to **lost accounts** or **further network staff intervention** neither of which are desirable outcomes.)_    
Can you _(or anyone else)_ provide any actual **PRO** use-cases for this functionality?

**Comment by mohdschizo** [comment]
@siniStar7boy 

an idea, what if u just put BlockSendPass in modules/contrib. for optional and not a core modules?

**Comment by GLolol** [comment]
I was poking around on the atheme forks tree, and found this which may be of interest: shaynejellesma/atheme@61b288ae25a83872d3679e432b828345473f9cba

**Comment by siniStar7boy** [comment]
There you go -- _the code exists_.  However, I have no plans to introduce this into Xtheme **or** even contrib at this time.

**Comment by siniStar7boy** [comment]
Added as of 7386a6784809f6248d1ee716c40af2dd9fecbbaf
