### ISSUE TITLE
REQUEST: Show Modifier/Setter in SOP/AOP/VOP/HOP output

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#16]
-ChanServ- SOP list for #channel :
-ChanServ- 1: user1 (not logged in) - added by Sinistar (1y 2w 3d)
-ChanServ- 2: user2 (logged in)       - added by Sinistar (2w 3d 4h)
-ChanServ- Total of 2 entries in SOP list of #channel.

This module will look simple, short, clean and easy to channel management to monitor channel access list.

**Comment by siniStar7boy** [comment]
_I'm just not seeing the necessity in this either._  It can already be better accomplished with **flags**, and improving the XOP functionality is not something that I am particularly worried about.
