### ISSUE TITLE
MODULE REQUEST : Chanserv Set MEMOLEVEL

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#18]
Usage: SET #<room> MEMOLEVEL [VOP|AOP|SOP|FOUNDER] 

-ChanServ- Flags      :  MEMOLEVEL(AOP)

------------------------------------------------------------------------------------------------------------------------------
This setting has a default of VOP when you register a room. You can however change the memolevel. A room memo is a memo sent to every registered nick in any of the room's lists or to everyone in a specified list such as AOP. This command lets you restrict who can send them to the people of your room.

Memos are useful for announcing policies or information everyone in the room might need. For example, if you do not add AOPs often, you could send a memo to the entire room informing them of a new AOP.

**Comment by GLolol** [comment]
:-1: XOP is legacy, and a more flexible way of doing this IMO is to add a flag for sending memos (e.g. `+m`).

**Comment by siniStar7boy** [comment]
I cannot see the use for this.  _(Especially XOP wise)_
