### ISSUE TITLE
MODULE REQUEST : NickServ Set MFORWARD [on|off] [<nick>]

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#19]
This command will redirect all memos arriving to the nickname you are using to a new nickname that you specify. You need to be identified to both nicknames in order to enable this command. If you set MFORWARD OFF it will stop forwarding memos for the nick you are using. You cannot turn MFORWARD on if you have NOMEMO set on.

/msg nickserv set mforward on User1

/msg nickserv set mforward off

**Comment by GLolol** [comment]
> You need to be identified to both nicknames in order to enable this command. 

How? That's not possible.

**Comment by siniStar7boy** [comment]
Also un-necessary.  You could just Group the nicknames.
