### ISSUE TITLE
MODULE REQUEST : Chanserv Set ProtectOP

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#20]
SET PROTECTOP prevents channel operators from being deoped by anyone of
lower access level. For example: If a AOP, tried to kick a SOP, they would NOT be able to.

 Command Syntax:

 /msg ChanServ Set #channel ProtectOP on|off

-ChanServ- Flags      : ProtectOP

**Comment by GLolol** [comment]
On IRCds that support `&` and `~`, this is already done.

**Comment by siniStar7boy** [comment]
Agreed @GLolol  -- This can _(and should be)_ done at the ircd level.  **Another good point** is that if you don't trust a user or know them well; _you probably should not be opping them_

Closing, as this is really not necessary, nor does it necessarily "protect" a user ircd-wise.
