### ISSUE TITLE
MODULE REQUEST : Chanserv CHECKBAN

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#21]
Syntax: CHECKBAN channel

 This command tells you why you are banned from a channel.

#dwarf unable to join channel (address is banned)
-
-ChanServ- The ban guest*!*@* set by Dwarf prevents you from joining #dwarf.

**Comment by siniStar7boy** [comment]
Also un-necessary.  This can already be done ircd-side with ``/mode #channel b``    

Also, it could potentially help lamers evade bans.
