### ISSUE TITLE
chanserv/xop_manager.c

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#24]
cs_manager = MANAGER who can Manipulates a channel MANAGER list

**Comment by siniStar7boy** [comment]
Maro, I am not exactly sure what you are requesting here.  There is not a "manager" list in Xtheme, nor do I quite understand what it should accomplish or why it would be necessary??  What would be different from a Manager versus a user with a lot of "managerial" flags? 

**Please explain what cs_manager should accomplish, why it is necessary, and what managers are necessary for?**

**Comment by mohdschizo** [comment]
dear @siniStar7boy 

i think what @MrMaro mean with MANAGER are (maybe) almost the same like founder/cofounder flags. If founder/cofounder not around, the MANAGER can use almost the same flags to add/remove SOp/AOp/HOp/VOp/AKICK to a channel lis. MANAGER cannot DROP the channel. Only control it more like co-founder but limited flags.

Just my sense and logic.

**Comment by GLolol** [comment]
I think he's referring to something like https://bitbucket.org/chatlounge/chatservices/commits/202e862074056e4843e76d91fae465eb2be6b355, though what @mohdschizo describes can already be done with flags.

**Comment by mohdschizo** [comment]
Yes @GLolol you're perfectly right

**Comment by GLolol** [comment]
...That said, I don't really see any benefit of adding a module like this.

**Comment by siniStar7boy** [comment]
This is not necessary. _(at least at this time)_   Xtheme's access is _(as explained before)_ based on flags.    
Channel Access can already be fine-tuned by properly dispersing the correct flags _(or lack of them)_ per user.
