### ISSUE TITLE
Chanserv -> MKICK -> #channel

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#25]
Evacuates a channel completely by kicking everyone out, banning *!*@* (everyone), setting mode +i (invite only) and +l 1. When MKICKing a channel, you cannot UNBAN or INVITE yourself back into the channel.

Masskicks are limited to one an hour, and are only available to SOP's and Founders.

**Comment by GLolol** [comment]
Why would you want to lock yourself out of your own channel? I don't understand...

**Comment by MrMaro** [comment]
Mkick is usefull when flood/drone attack

**Comment by siniStar7boy** [comment]
I don't see any need or use for this.  Services Operators can already CLEAR USERS from a channel, but setting restrictive modes and locking everyone out?  Just deny the channel ircd side.
