### ISSUE TITLE
AKILL added time Operserv > AKILL List

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#27]
update akill list with time the AKILL has been added

example - by maro - time: 23/10/2015 - expires in 2 days, 0:23:56

**Comment by siniStar7boy** [comment]
Sounds useful to me.  

Anyone else find this useful or not useful?  _(Additional feedback would be appreciated)_

**Comment by GLolol** [comment]
:+1:

**Comment by siniStar7boy** [comment]
Fixed/Added via commit 458da29ce276ef921170de4e5bf194bf6b654733
