### ISSUE TITLE
setup error when i do -- make

### ISSUE THREAD

**Issue by ttadiga** [XthemeOrg/Xtheme#31]
ptasks.c: In function 'handle_stats':
ptasks.c:143: error: 'mowgli_eventloop_timer_t' has no member named 'deadline'
../buildsys.mk:319: recipe for target 'ptasks.lib.o' failed
gmake[1]: *** [ptasks.lib.o] Error 1
buildsys.mk:120: recipe for target 'libathemecore' failed
gmake: *** [libathemecore] Error 2
*** [.DEFAULT] Error code 2
![untitled](https://cloud.githubusercontent.com/assets/16384657/11978369/c05e298e-a993-11e5-95c8-895ed3ab2aa5.jpg)

**Comment by siniStar7boy** [comment]
I would recommend using a later _(more current)_ version of FreeBSD.
