### ISSUE TITLE
MODULE REQUEST: Chanserv USERINFO #channel activate/reject

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#34]
1. User who have +f or SOP in Channel can simple add USERINFO for other user who have access but not with +f or SOP. They can simple add anything they like in the USERINFO

2. User who have access but not with +f or SOP cant delete/reject the USERINFO that have been added

3. I would like to suggest that USERINFO should have command activate/reject and user have choice to select the best USERINFO for them

**Comment by siniStar7boy** [comment]
I do not see the need for this.  This could be abused or used to harass users and in other undesirable ways.  I'll leave it up for discussion for now.  If nobody has any compelling reasoning for this, it shall be closed.

**Comment by MrMaro** [comment]
i agree not many user use the command but my user still use the command. Some user dont want set userinfo but someone with +f set for them without they approval and they cant del the userinfo. User with +f abuse the command. Because of that, i think the command need to be add 'activate/reject' and get approval from the owner of the nick because userinfo can be use.

Or all user who have access in channel can DEL their userinfo not only user with +f

**Comment by MrMaro** [comment]
i agree not many user use the command but my user still use the command. Some user dont want set userinfo but someone with +f set for them without they approval and they cant del the userinfo. User with +f abuse the command. Because of that, i think the command need to be add 'activate/reject' and get approval from the owner of the nick before userinfo can be use.

Or all user who have access in channel can DEL their userinfo not only user with +f

**Comment by siniStar7boy** [comment]
Technically, however, this should have been opened in XthemeOrg/xtheme-contrib-modules issues tracker for cs_info.c.  Please feel free to post the issue there and reference this issue, but as this should have been filed there and is not an Xtheme core module - I am closing it for now.
