### ISSUE TITLE
InfoServ post | list

### ISSUE THREAD

**Issue by Casey952** [XthemeOrg/Xtheme#44]
InfoServ post and list has a different date and time display as per the NickServ ChanServ info etc etc date and time display.

If InfoServ could be made to have the post and list date and time display in-line with Services.

Services has it as:

Jun 01 00:00:00 2015

**Comment by siniStar7boy** [comment]
This is also _trivial_.  

The date&time format that the InfoServ posts use is intentional to throw less useless information to the user upon connect.  Adding additional characters has no benefit and could even result in characters available being decreased.
