### ISSUE TITLE
Channel Flag for Suspended users (P)

### ISSUE THREAD

**Issue by siniStar7boy** [XthemeOrg/Xtheme#47]
Xtheme 7.4.0 **Channel Access Suspension Flag (P)**.    

It appears that the Atheme Group contemplated this idea _(given that most Services packages have channel access suspensions)_ and it appears commented out in some areas.    

I am currently playing with the functionality, but have gone with channel suspension flag **P** which would allow channel Founders to suspend users rather than removing their flags during corrective actions for a duration of time or until manually removed.  

Discussion, feedback?

**Comment by GLolol** [comment]
Anyone with access to change the target's flags should be able to suspend/revoke their access. This means anyone with `+f`, unless `LIMITFLAGS` is set. Founders should always be exempt, in channels when there are more than one.

**Comment by siniStar7boy** [comment]
:+1: 

I was thinking along similar lines as far as the Founders.  If there is only one Founder then they were likely suspended, themselves by a Services Operator possessing the `chan:admin` priv.  If there is more than one, they can suspend/unsuspend each other as they please.

**Comment by GLolol** [comment]
> I was thinking along similar lines as far as the Founders. If there is only one Founder then they were likely suspended, themselves by a Services Operator possessing the chan:admin priv. 

There are already other ways of suspending channels. Where is the benefit of taking away a founder's access and still letting everyone else work? Network staff should minimally intervene in channel affairs IMO.

> I was thinking along similar lines as far as the Founders. If there is only one Founder then they were likely suspended, themselves by a Services Operator possessing the chan:admin priv. 

That just opens up abuse and drama. If one founder has to suspend the other, they shouldn't be co-owning a channel in the first place.

**Comment by siniStar7boy** [comment]
> There are already other ways of suspending channels. Where is the benefit of taking away a founder's access and still letting everyone else work? Network staff should minimally intervene in channel affairs IMO.

Yes there are, but this one _minimally_ impacts the channel if just the Founder is affected.  Other users with flags are still able to perform their duties.

> That just opens up abuse and drama. If one founder has to suspend the other, they shouldn't be co-owning a channel in the first place.

Possibly.  But in such a theoritcal setup, they want it like this or would only have one Founder.

**Comment by GLolol** [comment]
> Yes there are, but this one *minimally* impacts the channel if just the Founder is affected. Other users with flags are still able to perform their duties.

Nothing good can come out of this. If I own a channel somewhere and network staff decide to take my access, but let everyone else run wild, I would probably leave that network immediately. Like the `freeze` module, it turns things into anarchy - it can damage a channel's reputation if nobody is left to moderate.

**Comment by siniStar7boy** [comment]
> Nothing good can come out of this. If I own a channel somewhere and network staff decide to take my access, but let everyone else run wild, I would probably leave that network immediately. Like the freeze module, it turns things into anarchy - it can damage a channel's reputation if nobody is left to moderate.

If the founder is being abusive on the network and earns a suspension while the rest of his/her staff were not, then a suspension would be _ideal_.  And you are forgetting, there may be others in the channel with flags that ARE able to still moderate.

Per the ``freeze`` module, Networks that elect to use it should already be expecting to moderate frozen channels at the Services Operator level. (e.g. Kill/Xline spammers, etc)

**Comment by GLolol** [comment]
> And you are forgetting, there may be others in the channel with flags that ARE able to still moderate.

Not necessarily. Nothing forces them to give away access at all, in the first place.

> Networks that elect to use it should already be expecting to moderate frozen channels at the Services Operator level.

My point again is that network staff should minimally intervene in channel affairs. I doubt most opers would even bother to take over a channel, rather than just close it entirely.

**Comment by siniStar7boy** [comment]
If there are no other users with flags on the channel, even better reason for the Founder to ensure they don't get suspended.  _(Falls under nobody's problem but the Founder for getting themselves suspended anyway)_

With ``freeze``, we're drifting **off-topic** -- _yes_, networks typically prefer to minimize intervening in channel affairs -- those networks can ensure they do not load the ``Freeze`` module.

**Comment by siniStar7boy** [comment]
At this time, there is not a Services Operator FSUSPEND styled command.  

_If a demand for it is seen in  the future, it can be done._

Took @GLolol's advice and made the command available to those with ``+f``.
