### ISSUE TITLE
MODULE REQUEST : ChanServ MDEOP

### ISSUE THREAD

**Issue by selangor** [XthemeOrg/Xtheme#5]
same like DALnet server

# ChanServ > MDEOP

-ChanServ- ***** ChanServ Help *****
-ChanServ- Command - MDEOP
-ChanServ- Usage   - MDEOP <channel>
-ChanServ- Removes operator status from all users on the named channel.
-ChanServ- Limited to channel AutoOps and above.
-ChanServ- You cannot mass deop a channel with higher ranking ops in it than you.
-ChanServ- Example:
-ChanServ- /msg ChanServ MDEOP #channel
-ChanServ- ***** End of Help *****

### NOTE: This command would be added to ChanServ CLEAR, if implemented.  (e.g. /chanserv CLEAR #channelname OPS)

* Definitely up for more discussion of this feature request before (if) it is implemented.  Request modified as far as text and appearance.  Factual information has not been changed or removed.

**Comment by siniStar7boy** [comment]
# Feature Added as ChanServ CLEAR OPS
Thank you for the feedback.  

This has been added into Xtheme -- however with a few differences.  Channel Staff will need to have the **+R** flag in order to use this command. _(Mainly to prevent abuse and ensure that only high-level staff are able to issue the command)_

**Comment by GLolol** [comment]
Is this going to ever be merged upstream?

**Comment by siniStar7boy** [comment]
Yes.  Right now we're working on atheme release 7.2.7 which is intended to be mostly bug fixes.  

I would expect it as soon as we start on _new features_. (atheme ~7.3+)

**Comment by GLolol** [comment]
Sounds like it's time to multi-branch. \o/
