### ISSUE TITLE
Ns list forbidden

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#51]
I suggest xtheme should have forbidden list such as frozen list in the  /msg NickServ HELP LIST. Currently we cant track which nick has been forbid and list of them

Suggested command : /ns list forbidden

**Comment by siniStar7boy** [comment]
**Further feedback on this issue should take place on the XthemeOrg/xtheme-contrib-modules#5 topic.**

**Comment by siniStar7boy** [comment]
Closed with commits 497ed78d911e9bf257977861fe78d9044f405d5f and 87c731da2455d81302bf4e67db2fe0e118a2711b
