### ISSUE TITLE
New Suggestion For Nickserv Hold Command

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#52]
Current Situation: when admin set hold a nick, all nick in the same group will get hold. 

Suggestion: 

1. Hold command can be add for single nick. Other nick in the same group will not get the flags or it can have function to turn group hold on/off

2. Display/show who added the hold flags in the Nickserv INFO: Flags: hold added by Maro on ....

**Comment by siniStar7boy** [comment]
I would agree that suggestion 2 is reasonable and could be added, _but I disagree with changing the current functionality of the HOLD command as that bends backwards compatibility and/or causes issues for networks that were not aware of the change_.    

**Anyone have additional thoughts?**
