### ISSUE TITLE
Nickserv Watch : /msg NickServ WATCH <ADD|DEL|LIST> [nick]

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#57]
- Allows you to view and modify your NickServ watch list.
- You will be notified when a user on your watch list connects to IRC.
Syntax:
         WATCH ADD <nick>
         WATCH DEL <nick>
         WATCH LIST

- WATCH ADD adds the specified nick to your watch list. WATCH DEL deletes the specified nick from your   nick list. WATCH LIST displays your watch list.

**Comment by siniStar7boy** [comment]
As stated on IRC, just moments ago - almost _every_ IRC client has a notify list, or other [ircd] methods of doing this already.
