### ISSUE TITLE
Nickserv/Chanserv Auth : is used for reviewing and approving/rejecting channel access grants.

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#58]
ACCEPT - Approve the authorization request and memo the person confirmation.
APPROVE - Same as accept.
DECLINE - Decline the authorization request and memo the person that you will not be added to that channel list.
REJECT - Same as decline
LIST - List auth requests.
Syntax
AUTH [nick] <LIST|ACCEPT|DECLINE> [num|chan]

**Comment by siniStar7boy** [comment]
We've already discussed this request as well.  This would be too much of a burden to Xtheme _(Services)_ on networks with a decent user-base.  

If a user does not want access assigned to them without their permission, they can set **NEVEROP** which will _disallow them from being added to access lists without their permission_.  **When they approve of being given access to a channel, they can _unset it while the access is being exchanged_ and _then set it back_**.
