### ISSUE TITLE
immune not working

### ISSUE THREAD

**Issue by selangor** [XthemeOrg/Xtheme#6]
Hello..
I use inspircd2.0.20 and use xtheme 7.3.1
I already set immune..
But normal user can !kick oper..
Can u fix it?

 *    immune - require whatever ircd usermode is needed for kick
 *             immunity (this is the default);

 immune_level = immune;

**Comment by siniStar7boy** [comment]
This bug does not exist, or could not be reproduced using the latest InspIRCd git version.  

On **InspIRCd-2.0.20**, setting **+Y** _(oper immune)_ on yourself and then asking a lower level operator to !kick you produces:
`` -ChanServ:#Test- Not kicking oper siniStar ((someone) testing)``

Closing this issue.
