### ISSUE TITLE
/ns fgroup

### ISSUE THREAD

**Issue by Yorgosgr** [XthemeOrg/Xtheme#62]
Hello,

Seeing that we have /ns fungroup i think it would be wise to add the /ns fgroup too.

Thank you.

**Comment by siniStar7boy** [comment]
After more thought and just generally not having interest in this module (or demand), plus my own concerns about it being abused - I am closing this issue.

**Comment by siniStar7boy** [comment]
Implemented in v8.0.0-dev6
