### ISSUE TITLE
Bring Back /cs set #channel Successor

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#69]
Currently channel Successor is randomly pick by services and channel founder did not have control for it. I think channel founder should be given more freedom to add a specific nick to channel Successor

With that, i would like to suggest xtheme to bring back the command /cs set #channel Successor

TQ

**Comment by olson86** [comment]
I do agree that this is a feature that should be there. Most services have this. - Karion

**Comment by siniStar7boy** [comment]
This was _never_ an upstream command of atheme or Xtheme.  _(You are probably thinking of Anope..)_ 
   
However, the functionality that you desire **already exists**, as we've discussed.    

You should enable the `chanserv/successor_acl` module, granting you the ability to add the **+S flag** on users in channels that you want, to be the successor.  `/msg ChanServ FLAGS #channel MySuccessor +S`    

At this time, I do not see the need for a SET SUCCESSOR command - as **this functionality already is available as described above**.
