### ISSUE TITLE
/ns sendpass failed

### ISSUE THREAD

**Issue by selangor** [XthemeOrg/Xtheme#7]
Hello..
My user lost password.. i already /ns sendpass exco
But email send failed
Can u fix it?

I already set

mta = "/usr/sbin/sendmail";

*** GLOBOPS: From services.********: sendemail(): email for selangor[selangor@staff.******] (103.1.69.238) type setpass to exco <shahrul@doctor.com>
 -NickServ-: Email send failed.

**Comment by siniStar7boy** [comment]
This has been fixed in the latest git version.  Please re-clone from git.
