### ISSUE TITLE
open to vulnerabilities -> password shown in debug.log as clear text

### ISSUE THREAD

**Issue by fgrosswig** [XthemeOrg/Xtheme#70]
it would be good if you would at least salt or decrypt passwords for any instance like register/identify/login or whatsover in the debug.log.

Consider this as critical risk.

:-)

**Comment by siniStar7boy** [comment]
This is actually the intended behavior.  Nobody without proper access should be able to login to the box that Xtheme is running on, except the Operator/Admin running Services.. _(Which if they are not trustworthy not to put Xtheme into debug mode and then check debug.log for passwords, then they should not be running the Services box)_

Closing as this is the intended behavior and not really a security risk so much as Services Administrator should be trust-worthy to run Services, else they should not have access to the box.  It may be reconsidered in the future, however.
