### ISSUE TITLE
Mass Akill For Channel

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#73]
/os MASSKILLCHAN - AKILLs all users in a channel <-- very usefull to akill clone/drone/flooding in a channel. With this command all bot/users in the channel will get banned.

-OperServ- AKILLCHAN       AKILLs all users joining a channel. <-- only kill user joinning a channel

**Comment by GLolol** [comment]
Isn't this doable with `/os clearchan akill` for the first use case and `/os klinechan` (from contrib) for the second?

**Comment by siniStar7boy** [comment]
This is already possible using OperServ CLEARCHAN with the AKILL option.  

All users on channel _(who are not IRC Operators)_ will be AKILLed from the network.
