### ISSUE TITLE
vhost_change is not working in xtheme 8.0.0-dev2

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#82]
vhost_change is not working and user can apply vhost more then one time in a day.

**Comment by siniStar7boy** [comment]
After repeated testing, this cannot be reproduced unless the vhost_change setting is misplaced in the xtheme.conf.  The **vhost_change** setting must be placed inside the **general {}** block.  

**Please reference:**  
https://github.com/XthemeOrg/Xtheme/blob/master/dist/xtheme.conf.example#L2179-#L2186  
To see where Xtheme's current example config uses it, and when uncommented and given a number value; it works as designed. :)  _(**just numbers**, no h/d/m after the number value)_
