### ISSUE TITLE
Restrict Nick Per Email 

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#83]
How many nick can be register using one email address. This setting is for nick registration security to avoid clone/drone/user register so many nick with one single email address.

**Comment by siniStar7boy** [comment]
This is already possible in the HostServ or general block.

**Comment by MrMaro** [comment]
Which part in the config can be set for nick per email

**Comment by MrMaro** [comment]
In hostserv, i can see at #request_per_nick; but i cant find any in general block

**Comment by siniStar7boy** [comment]
Check under general { then, and look for maxusers

**Comment by siniStar7boy** [comment]
https://github.com/XthemeOrg/Xtheme/blob/master/dist/xtheme.conf.example#L1002-#L1006

**Comment by MrMaro** [comment]
ok noted tq
