### ISSUE TITLE
MODULE REQUEST : Nickserv SET BLOCKSENDPASS

### ISSUE THREAD

**Issue by MrMaro** [XthemeOrg/Xtheme#84]
SET BLOCKSENDPASS allows you to block
the ability of a SENDPASS being used 
on your account from a user without
IRC Operator access.

Syntax: SET BLOCKSENDPASS <ON|OFF>

**Comment by siniStar7boy** [comment]
This has already been brought up and discussed - #14 -- however, let's leave this open for Discussion.
