### ISSUE TITLE
Not automatically changed to guest, Enforce

### ISSUE THREAD

**Issue by gorut** [XthemeOrg/Xtheme#89]
nickserv {
        spam;
        #no_nick_ownership;
        nick = "NickServ";
        user = "NickServ";
        host = "Services.indowork.org";
        real = "Nickname Services";
        aliases {
                "ID" = "IDENTIFY";
                "MYACCESS" = "LISTCHANS";
        };
        access {
        };
        maxnicks = 3;
        expire = 900;
        #enforce_expire = 14;
        enforce_delay = 30;
        enforce_prefix = "Guest";
        emailexempts {
        };
};

after the seconds have passed, nick is not automatically changed to Guest
what's the solution?

**Comment by siniStar7boy** [comment]
Services server needed to be U-Lined.  The issue is resolved.  

Thanks for using Xtheme IRC Services.
