### ISSUE TITLE
Show the number of affected users with ChanServ BAN and AKICK commands

### ISSUE THREAD

**Issue by man-d67** [XthemeOrg/Xtheme#90]
HI,
Show the number of affected users like OperServ AKILL does but also when ChanServ BAN or AKICK commands are used.
Thanks

**Comment by siniStar7boy** [comment]
While I generally like the idea, it would be more costly to larger networks than it is worth. (Memory & CPU)

**Thanks for suggesting the idea** -- _it may still be considered at a later time in the future_.
